### ISSUE TITLE
Audio item has no derivatives

### ISSUE THREAD

**Issue by glenrobson** [internetarchive/iiif#54]
Transfered from: https://github.com/ArchiveLabs/iiif.archivelab.org/issues/126

I can't say why, but this item has no audio derivatives created, which means the code logic is not generating any items for the v3 manifest: 

* Metadata: https://archive.org/metadata/kaled_jalil
* Details page: https://archive.org/details/kaled_jalil
* Manifest: https://iiif.archive.org/iiif/3/kaled_jalil/manifest.json (500 error)

While it's an edge case, I've seen in the help docs that it is possible for uploaders tor request that all IA-created derivatives be removed from an item, say in the case where a user only wants the lossless files they uploaded to appear as options. 

Since there are still playable files -- in this case, valid mp3s -- we should figure out how to handle this logic.

**Comment by glenrobson** [comment]
Stack trace:

```
Traceback (most recent call last):
  File "/Users/gmr/development/ia-iiif/.venv/lib/python3.12/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmr/development/ia-iiif/.venv/lib/python3.12/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmr/development/ia-iiif/.venv/lib/python3.12/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmr/development/ia-iiif/.venv/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmr/development/ia-iiif/.venv/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmr/development/ia-iiif/.venv/lib/python3.12/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmr/development/ia-iiif/.venv/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmr/development/ia-iiif/.venv/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmr/development/ia-iiif/.venv/lib/python3.12/site-packages/flask_caching/__init__.py", line 404, in decorated_function
    rv = self._call_fn(f, *args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmr/development/ia-iiif/.venv/lib/python3.12/site-packages/flask_caching/__init__.py", line 180, in _call_fn
    return ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmr/development/ia-iiif/iiify/app.py", line 200, in manifest3
    raise excpt
  File "/Users/gmr/development/ia-iiif/iiify/app.py", line 193, in manifest3
    return ldjsonify(create_manifest3(identifier, domain=domain, page=page))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gmr/development/ia-iiif/iiify/resolver.py", line 707, in create_manifest3
    anno.body = body
                ^^^^
UnboundLocalError: cannot access local variable 'body' where it is not associated with a value
```
